<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>x500_nav3d</name>
  <version>0.1.0</version>
  <description>Metapackage for the PX4 X500 description and MoveIt configuration.</description>
  <maintainer email="salvatoredelpeschio@gmail.com">Salvatore Del Peschio</maintainer>
  <license>MIT</license>

  <url type="repository">https://github.com/saviodp7/x500_nav3d</url>
  <url type="bugtracker">https://github.com/saviodp7/x500_nav3d/issues</url>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>x500_description</exec_depend>
  <exec_depend>x500_moveit_config</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
